.\" Copyright (C) 2004, 2005  Dmitry V. Levin <ldv@altlinux.org>
.\" 
.\" Documentation for the hasher-useradd program.
.\"
.\" This file is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

[NAME]
\fBhasher\-useradd\fR \- create hasher satellite users

[SEE ALSO]
.BR hsh (1),
.BR hasher\-priv.conf (5),
.BR hasher (7),
.BR useradd (8).
